# Configuration file for the LoCoDiff benchmark pipeline

# Languages configuration - maps languages to their associated file extensions used in prompt generation
languages:
  python:
    extensions:
      - .py
  javascript:
    extensions:
      - .js
      - .jsx
  typescript:
    extensions:
      - .ts
      - .tsx
  zig:
    extensions:
      - .zig
  rust:
    extensions:
      - .rs

# Model display name mappings - used to rename models in the visualization for clarity
# Maps the original model name (as used in OpenRouter) to a display name for charts and tables
model_display_names:
  "anthropic/claude-3.5-sonnet": "Sonnet 3.6"
  "anthropic/claude-3.7-sonnet": "Sonnet 3.7"
  "anthropic/claude-3.7-sonnetthinking": "Sonnet 3.7 Thinking"
  "anthropic/claude-sonnet-4": "Sonnet 4"
  "anthropic/claude-sonnet-4thinking": "Sonnet 4 Thinking"
  "openai/gpt-4.1": "GPT-4.1"
  "openai/o4-mini-high": "o4-mini-high"
  "openai/o4-mini": "o4-mini-medium"
  "openai/o3": "o3"
  "deepseek/deepseek-chat-v3-0324": "DeepSeek Chat v3-0324"
  "deepseek/deepseek-r1": "DeepSeek R1"
  "deepseek/deepseek-r1-0528": "DeepSeek R1 0528"
  "google/gemini-2.5-flash-preview": "Gemini 2.5 Flash"
  "google/gemini-2.5-flash-previewthinking": "Gemini 2.5 Flash Thinking"
  "google/gemini-2.5-pro-preview": "Gemini 2.5 Pro 05-06"
  "google/gemini-2.5-pro-preview-03-25": "Gemini 2.5 Pro 03-25"
  "google/gemini-2.5-pro-preview-06-05": "Gemini 2.5 Pro 06-05"
  "x-ai/grok-3-beta": "Grok 3"
  "x-ai/grok-3-mini-beta": "Grok 3 Mini"
