# Configuration file for the LoCoDiff benchmark pipeline

# Languages configuration - maps languages to their associated file extensions used in prompt generation
languages:
  python:
    extensions:
      - .py
  javascript:
    extensions:
      - .js
      - .jsx
  typescript:
    extensions:
      - .ts
      - .tsx
  zig:
    extensions:
      - .zig

# Model display name mappings - used to rename models in the visualization for clarity
# Maps the original model name (as used in OpenRouter) to a display name for charts and tables
model_display_names:
  "anthropic/claude-3.5-sonnet": "Sonnet 3.6"
  "anthropic/claude-3.7-sonnetthinking": "Sonnet 3.7 Thinking"
  "openai/gpt-4.1": "GPT-4.1"
  "openai/o4-mini-high": "o4-mini-high"
  "openai/o4-mini": "o4-mini-medium"
  "deepseek/deepseek-chat-v3-0324": "DeepSeek Chat v3-0324"
  "deepseek/deepseek-r1": "DeepSeek R1"
