name: Format and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv pip install --system -r requirements.txt
    
    - name: Run ruff formatter
      run: |
        uv pip install --system ruff
        ruff format --check .
    
    - name: Run ruff linter
      run: |
        ruff check .
    
    - name: Run type checking with pyright
      run: |
        uv pip install --system pyright
        pyright utils.py
