name: Format and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install Python and Dependencies using uv
      run: |
        uv python install 3.12.3
        uv venv --python 3.12.3
        # Activate venv for this step to install into it
        source .venv/bin/activate
        uv pip install -r requirements.txt
        echo "Python version in venv:"
        python --version
        echo "Ruff version in venv:"
        ruff --version
        echo "Pyright version in venv:"
        pyright --version

    - name: Run ruff formatter
      run: |
        source .venv/bin/activate
        echo "Running ruff format check..."
        ruff format --check .

    - name: Run ruff linter
      run: |
        source .venv/bin/activate
        echo "Running ruff lint check..."
        ruff check .

    - name: Run type checking with pyright
      run: |
        source .venv/bin/activate
        echo "Running pyright type check..."
        pyright . # Check the whole project
